CURR_DIR = $(shell pwd)
include $(CURR_DIR)/make.common

ifeq ($(strip $(BRCM_BOARD_ID)),"947189cyrus")
BUILD_PLUME_IMAGE = y
endif
ifeq ($(strip $(BRCM_BOARD_ID)),"96755augustus")
BUILD_PLUME_IMAGE = y
endif
ifeq ($(strip $(BRCM_BOARD_ID)),"96755pathos")
BUILD_PLUME_IMAGE = y
endif

ifeq ($(strip $(BUILD_PLUME_IMAGE)),y)
cleanup_image:
	@echo -e "Removing unused files from staging"
	@rm -rf ${PROFILE_DIR}/fs/webs/
	@rm -f ${PROFILE_DIR}/fs/bin/openssl
	@rm -f ${PROFILE_DIR}/fs/bin/sqlite3
	@rm -f ${PROFILE_DIR}/fs/lib/libsqlite3.so*
	@echo -e "remove .a XXX"
	@find ${PROFILE_DIR}/fs/ -name "*.a" -or -name "*.la" | xargs rm -f
	@rm -f ${PROFILE_DIR}/fs/lib/libjpeg.so*

ENCKEY := $(shell openssl rand -base64 32)

buildimage_final:
	$(eval $@PLUME_VER := $(shell cat $(PROFILE_DIR)/fs/.version | cut -d\  -f1))
	$(eval $@RENAME_PROFILE=$(patsubst %_BCM52,%_BCM527,$(OPENSYNC_TARGET)))

	@echo -e "Renaming to Plume image naming style"
	@find $(IMAGES_DIR) -name bcm$(PROFILE)_*$(CUR_TS)* -printf "%f\n" | \
		while read name; \
		do \
			NEW_NAME="$${name}"; \
			NEW_NAME="$${NEW_NAME/bcm$(PROFILE)_/bcm$($@RENAME_PROFILE)_}"; \
			NEW_NAME="$${NEW_NAME/_$${BRCM_RELEASETAG}-$${CUR_TS}/-$($@PLUME_VER)}" ; \
			NEW_NAME="$${NEW_NAME/\.w/\.img}" ; \
			mv $(IMAGES_DIR)/$${name} $(IMAGES_DIR)/$${NEW_NAME} ; \
			(cd $(IMAGES_DIR) && md5sum "$${NEW_NAME}" > "$${NEW_NAME}.md5.save") ; \
			\
			if echo $$NEW_NAME | grep -q '_nand_.*fs_image_.*\.img$$'; \
			then \
				ENC_NAME="$${NEW_NAME%.img}.eim"; \
				openssl enc -aes-256-cbc -pass pass:$(ENCKEY) -md sha256 -nosalt -in "$(IMAGES_DIR)/$${NEW_NAME}" -out "$(IMAGES_DIR)/$${ENC_NAME}" ; \
				echo ${ENCKEY} > "$(IMAGES_DIR)/$${ENC_NAME}.key" ; \
				(cd $(IMAGES_DIR) && md5sum "$${ENC_NAME}" > "$${ENC_NAME}.md5.save") ; \
			fi \
		done
else
cleanup_image:
	true
buildimage_final:
	true
endif
