#
# Linux WBD Makefile
#
# Copyright (C) 2018, Broadcom. All Rights Reserved.
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
# SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION
# OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN
# CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#
# $Id: Makefile 721357 2017-09-14 04:44:33Z $
#

CURR_DIR := $(shell pwd)
BUILD_DIR=$(word 1, $(subst /bcmdrivers, /bcmdrivers,$(shell pwd)))
#include $(BUILD_DIR)/make.common
-include $(KERNEL_DIR)/.config
export CFLAGS

ifeq ($(strip $(BUILD_1905_NOCMS)),)
export WBD_REQ_CMS_LIBS :=-lcms_util -lbcm_util -lbcm_flashutil -lbcm_boardctl -lgen_util -lsys_util -lcrypt -lrt  -lcms_msg
ifneq ($(BRCM_1905_TOPOLOGY_WEB_PAGE),)
CFLAGS += -I$(BCM_FSBUILD_DIR)/public/include
CFLAGS += -I$(BCM_FSBUILD_DIR)/public/include/websockets
CFLAGS += -I$(BUILD_DIR)/userspace/public/libs/httpdshared
export WBD_REQ_CMS_LIBS += -lwebsockets -lssl -lcrypto -lhttpdshared $(CMS_CORE_LIBS) -lcms_dal -ldl
endif

else
export WBD_REQ_CMS_LIBS :=-lbcm_util -lbcm_flashutil -lbcm_boardctl -lgen_util -lsys_util -lcrypt -lrt 
endif


dirs = cli slave master
#WBDINSTALLDIR = $(INSTALLDIR)/wbd
WBDINSTALLDIR = $(INSTALLDIR)
PREBUILTDIR = prebuilt
LIBWBDSHARED = $(PREBUILTDIR)/libwbdshared.so-$(EXT_CPU_ARCH_NAME)
WBDMASTER = $(PREBUILTDIR)/wbd_master-$(EXT_CPU_ARCH_NAME)
WBDSLAVE = $(PREBUILTDIR)/wbd_slave-$(EXT_CPU_ARCH_NAME)
WBDCLI = $(PREBUILTDIR)/wb_cli-$(EXT_CPU_ARCH_NAME)
WBDWWW = ./www
WBDPAGES += $(WBDWWW)/wbd_demo.asp $(WBDWWW)/wbd_demo.css $(WBDWWW)/wbd_demo.js

ifneq ($(strip $(BUILD_ETHSWCTL)),)
export LDFLAGS +=  -lethswctl
endif

ifeq ($(PLC_WBD),1)
export CFLAGS += -DPLC_WBD
endif

CFLAGS  += -DWL11AC_160

DOXY_PATH = dox
DOXY_FILE = wbd.conf

.PHONY: all $(dirs) shared
all: $(dirs)

$(dirs): shared
	if [ -e $@/Makefile.dslcpe ]; then \
	$(MAKE) -C $@ -f Makefile.dslcpe install || exit $$? ; \
	fi

shared: $(PREBUILTDIR)
	if [ -e shared/Makefile.dslcpe ]; then \
	$(MAKE) -C shared -f Makefile.dslcpe install || exit $$? ; \
	fi

$(PREBUILTDIR):
	install -d $(PREBUILTDIR)
.PHONY: install
install: all
	install -d $(PREBUILTDIR)

	install -d $(WBDINSTALLDIR)/bin/
	install -d $(WBDINSTALLDIR)/webs/wlrouter
	install -m 755 $(LIBWBDSHARED) $(WBDINSTALLDIR)/lib/libwbdshared.so
	install -m 755 $(WBDMASTER) $(WBDINSTALLDIR)/bin/wbd_master
	install -m 755 $(WBDSLAVE) $(WBDINSTALLDIR)/bin/wbd_slave
	install -m 755 $(WBDCLI) $(WBDINSTALLDIR)/bin/wb_cli
	install -m 644 $(WBDPAGES) $(WBDINSTALLDIR)/webs/wlrouter

.PHONY: doc
doc:
	doxygen $(DOXY_FILE)

.PHONY: clean shared_clean
clean: shared_clean
	@for i in $(dirs); do \
		[ ! -d $$i ] || $(MAKE) -C $$i -f Makefile.dslcpe clean ; \
	done
	rm -rf $(DOXY_PATH)
shared_clean:
	if [ -e shared/Makefile.dslcpe ]; then \
	$(MAKE) -C shared -f Makefile.dslcpe clean || exit $$? ; \
	fi
