#***********************************************************************
#
#  Copyright (c) 2014  Broadcom Corporation
#  All Rights Reserved
#
#  <:label-BRCM:2014:proprietary:standard
#  
#   This program is the proprietary software of Broadcom and/or its
#   licensors, and may only be used, duplicated, modified or distributed pursuant
#   to the terms and conditions of a separate, written license agreement executed
#   between you and Broadcom (an "Authorized License").  Except as set forth in
#   an Authorized License, Broadcom grants no license (express or implied), right
#   to use, or waiver of any kind with respect to the Software, and Broadcom
#   expressly reserves all rights in and to the Software and all intellectual
#   property rights therein.  IF YOU HAVE NO AUTHORIZED LICENSE, THEN YOU HAVE
#   NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD IMMEDIATELY NOTIFY
#   BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
#  
#   Except as expressly set forth in the Authorized License,
#  
#   1. This program, including its structure, sequence and organization,
#      constitutes the valuable trade secrets of Broadcom, and you shall use
#      all reasonable efforts to protect the confidentiality thereof, and to
#      use this information only in connection with your use of Broadcom
#      integrated circuit products.
#  
#   2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
#      AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
#      WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH
#      RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND
#      ALL IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT,
#      FITNESS FOR A PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR
#      COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE
#      TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR
#      PERFORMANCE OF THE SOFTWARE.
#  
#   3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR
#      ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL,
#      INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY
#      WAY RELATING TO YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN
#      IF BROADCOM HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES;
#      OR (ii) ANY AMOUNT IN EXCESS OF THE AMOUNT ACTUALLY PAID FOR THE
#      SOFTWARE ITSELF OR U.S. $1, WHICHEVER IS GREATER. THESE LIMITATIONS
#      SHALL APPLY NOTWITHSTANDING ANY FAILURE OF ESSENTIAL PURPOSE OF ANY
#      LIMITED REMEDY.
:>
#
#***********************************************************************/

#
# In most cases, you only need to modify this first section.
#

EXE   = mhd
OBJS  = mhd.o mhd_cmd.o

all dynamic install : conditional_build


#
# Set our CommEngine directory (by splitting the pwd into two words
# at /userspace and taking the first word only).
# Then include the common defines under CommEngine.
# You do not need to modify this part.
#
CURR_DIR := $(shell pwd)
BUILD_DIR:=$(subst /userspace, ,$(CURR_DIR))
BUILD_DIR:=$(word 1, $(BUILD_DIR))

include $(BUILD_DIR)/make.common

LIBS   = -L$(INSTALL_DIR)/lib -lmicrohttpd

ifeq ($(strip $(BRCM_USER_SSP)),y)
LIBS   += -L$(INSTALL_DIR)/lib $(SSP_LIBS) 
CFLAGS += $(SSP_TYP_COMPILER_OPTS)
endif

ifneq ($(strip $(BUILD_MICRO_HTTPD)),)
conditional_build: $(EXE) generic_exe_install web_install
else
conditional_build: sanity_check
	@echo "Skipping $(EXE) (MICRO_HTTPD not configured)"
endif

clean: generic_clean
	rm -f $(INSTALL_DIR)/bin/$(EXE)
	rm -f $(INSTALL_DIR)/webs/ee_install.html
	rm -f $(INSTALL_DIR)/webs/logo.html
	rm -f $(INSTALL_DIR)/webs/mhd-main.html
	rm -f $(INSTALL_DIR)/webs/mhd-menu.html
	rm -f $(INSTALL_DIR)/webs/footer.html
	rm -f $(INSTALL_DIR)/webs/util.js
	rm -f $(INSTALL_DIR)/webs/tabletab.css
	rm -f $(INSTALL_DIR)/webs/logo.png
	rm -f $(INSTALL_DIR)/webs/logo-line-left.png
	rm -f $(INSTALL_DIR)/webs/logo-line-right.png
	rm -f $(INSTALL_DIR)/etc/init.d/mhd.sh
	rm -f $(INSTALL_DIR)/etc/rc3.d/S70mhd
	rm -f $(INSTALL_DIR)/etc/rc3.d/K30mhd

binaryonly_dist_clean: clean generic_binaryonly_dist_clean
	rm -f Makefile.fullsrc

web_install:
	cp -f ee_install.html $(INSTALL_DIR)/webs
	cp -f logo.html $(INSTALL_DIR)/webs
	cp -f mhd-main.html $(INSTALL_DIR)/webs
	cp -f mhd-menu.html $(INSTALL_DIR)/webs
	cp -f footer.html $(INSTALL_DIR)/webs
	cp -f util.js $(INSTALL_DIR)/webs
	cp -f tabletab.css $(INSTALL_DIR)/webs
	cp -f logo.png $(INSTALL_DIR)/webs
	cp -f logo-line-left.png $(INSTALL_DIR)/webs
	cp -f logo-line-right.png $(INSTALL_DIR)/webs
	mkdir -p $(INSTALL_DIR)/etc/init.d
	mkdir -p $(INSTALL_DIR)/etc/rc3.d
	install -m 0755 scripts/mhd.sh $(INSTALL_DIR)/etc/init.d
	(cd $(INSTALL_DIR)/etc/rc3.d; rm -f S70mhd; ln -s ../init.d/mhd.sh S70mhd)
	(cd $(INSTALL_DIR)/etc/rc3.d; rm -f K30mhd; ln -s ../init.d/mhd.sh K30mhd)

shell:
	bash -i


#
# Private apps and libs are allowed to include from private and public.
#
# WARNING: Do not modify this section unless you understand the
# license implications of what you are doing.
#
ALLOWED_INCLUDE_PATHS := -I. -I..\
						 -I$(BUILD_DIR)/shared/opensource/include/bcm963xx/ \
                         -I$(BUILD_DIR)/userspace/public/include  \
                         -I$(BUILD_DIR)/userspace/public/include/$(OALDIR) \
                         -I$(BUILD_DIR)/userspace/private/include  \
                         -I$(BUILD_DIR)/userspace/private/include/$(OALDIR) \
                         -I$(BCM_FSBUILD_DIR)/public/include \
                         -I$(BCM_FSBUILD_DIR)/private/include \
                         -I$(INC_BRCMDRIVER_PUB_PATH)/$(BRCM_BOARD) \
                         -I$(INC_BRCMDRIVER_PRIV_PATH)/$(BRCM_BOARD)


#
# Private apps and libs are allowed to link with libraries from the
# private and public directories.
#
# WARNING: Do not modify this section unless you understand the
# license implications of what you are doing.
#
ALLOWED_LIB_DIRS := /lib:/lib/private:/lib/public

# Set flags if user wants to link with OpenSSL
ifneq ($(strip $(DO_BUILD_OPENSSL)),)
CFLAGS += -DUSE_SSL -DORIGINAL_OPENSSL
LIBS += -lssl -lcrypto
endif

# treat all warnings as errors
CUSTOM_CFLAGS += -Werror -Wfatal-errors


#
# Implicit rule will make the .c into a .o
# Implicit rule is $(CC) -c $(CPPFLAGS) $(CFLAGS)
# See Section 10.2 of Gnu Make manual
# 
$(EXE): $(OBJS)
	$(CC) $(BCM_LD_FLAGS) -o $@ $(OBJS) $(LIBS)


#
# Include the rule for making dependency files.
# The '-' in front of the second include suppresses
# error messages when make cannot find the .d files.
# It will just regenerate them.
# See Section 4.14 of Gnu Make.
#

include $(BUILD_DIR)/make.deprules

-include $(OBJS:.o=.d)


