#
# Linux Makefile
#
# Copyright (C) 2017, Broadcom Corporation
# All Rights Reserved.
#
# This is UNPUBLISHED PROPRIETARY SOURCE CODE of Broadcom Corporation;
# the contents of this file may not be disclosed to third parties, copied
# or duplicated in any form, in whole or in part, without the prior
# written permission of Broadcom Corporation.
#
# $Id: Makefile 341899 2012-06-29 04:06:38Z $
#

.PHONY: all clean install

include $(KERNEL_DIR)/.config

ifeq ($(INSTALLDIR),)
$(error INSTALLDIR not defined)
endif

export SWSAVER = 2.6
SWSALIB = libairiq
SWSALIB_SO = $(SWSALIB).so.$(SWSAVER)
SIRPLIB = libairiq_sirp
SIRPLIB_SO = $(SIRPLIB).so.$(SWSAVER)

export PLATFORM=$(shell echo $(EXT_CPU_ARCH_NAME))

export AIRIQ_COMPONENTDIR =$(CURDIR)
$(info Building Air-IQ version $(SWSAVER) INSTALLDIR=$(INSTALLDIR))
$(info SRCBASE=$(SRCBASE) AIRIQ_COMPONENTDIR=$(AIRIQ_COMPONENTDIR) CURDIR=$(CURDIR))
$(info PLATFORM=$(PLATFORM))

all: airiq_app

airiq_app: ./prebuilt/$(PLATFORM)/$(SWSALIB).so
	$(MAKE) -C src/app -f Makefile.dslcpe

./prebuilt/$(PLATFORM)/$(SWSALIB).so:
ifneq ($(wildcard src/internal/Makefile.dslcpe),)
	$(MAKE) -C src/internal -f Makefile.dslcpe
else
	@ln -sf  ./$(SIRPLIB_SO) ./prebuilt/$(PLATFORM)/$(SIRPLIB).so
	@ln -sf  ./$(SWSALIB_SO) ./prebuilt/$(PLATFORM)/$(SWSALIB).so
endif

clean:
ifneq ($(wildcard src/internal/Makefile.dslcpe),)
	$(MAKE) -C src/internal c -f Makefile.dslcpe clean
endif
	@find -name \*.o|xargs rm -rf
	$(MAKE) -C src/app -f Makefile.dslcpe clean
	-rm -rf $(INSTALLDIR)/usr/sbin/airiq*
	-rm -rf $(INSTALLDIR)/usr/lib/libairiq*
	-rm -rf $(INSTALLDIR)/etc/airiq*

install: all
	# Install Air-IQ service and .cfg file
	install -d $(INSTALLDIR)/usr/sbin
	install -m 755 ./prebuilt/$(PLATFORM)/airiq_service $(INSTALLDIR)/usr/sbin
	install -m 555 ./prebuilt/$(PLATFORM)/airiq_service.cfg $(INSTALLDIR)/usr/sbin
	install -m 555 ./prebuilt/$(PLATFORM)/flash_policy.xml $(INSTALLDIR)/usr/sbin
	# Install Air-IQ libraries and .cfg file
	install -d $(INSTALLDIR)/usr/lib
	install -m 755  ./prebuilt/$(PLATFORM)/$(SWSALIB_SO) $(INSTALLDIR)/usr/lib/$(SWSALIB_SO)
	ln -sf ./$(SWSALIB_SO) $(INSTALLDIR)/usr/lib/libairiq.so
	install -m 755  ./prebuilt/$(PLATFORM)/$(SIRPLIB_SO) $(INSTALLDIR)/usr/lib/$(SIRPLIB_SO)
	ln -sf ./$(SIRPLIB_SO) $(INSTALLDIR)/usr/lib/libairiq_sirp.so
	install -d $(INSTALLDIR)/etc
	install -m 555 ./prebuilt/$(PLATFORM)/airiq.cfg $(INSTALLDIR)/etc
	# Install Air-IQ app
	install -d $(INSTALLDIR)/webs/wlrouter
	install  ./www/* $(INSTALLDIR)/webs/wlrouter
	make -C src/app -f Makefile.dslcpe install
